name: Compilar Mod 1.20.1
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Eliminar archivo corrupto del autor
        run: rm -f gradle/wrapper/gradle-wrapper.jar

      - name: Configurar Gradle 8.0 Oficial Seguro
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.0.2
          validate-wrapper: false

      - name: Dar permisos de administrador a Gradle
        run: chmod +x gradlew

      - name: Construir archivo JAR
        run: ./gradlew build --no-daemon

      - name: Guardar Mod Listo
        uses: actions/upload-artifact@v4
        with:
          name: MiMod1.20.1
          path: build/libs/*.jar
